### ISSUE TITLE
Update to Cake 0.23

### ISSUE THREAD

**Issue by kcamp** [cake-contrib/Cake.Grunt#4]
Current 0.1.0 version of Cake.Grunt is not compatible with Cake 0.22+ and should be updated for the most current version.

**Comment by kcamp** [comment]
Apologies for bumping this, but any chance of getting this reviewed/merged in the near future?  Thanks.

**Comment by gep13** [comment]
@kcamp sorry for the slight delay in getting this out.

Would you be interested in helping out with this addin?  I am sure that @Tanzy would welcome the help.

I have just pushed out 0.2.0 of Cake.Grunt.

**Comment by Tanzy** [comment]
Sorry, for some reason I did not get any notification about this :|

**Comment by gep13** [comment]
>@Tanzy said...
Sorry, for some reason I did not get any notification about this :|

Not a problem at all.
